### ISSUE TITLE
Fatal Error DABRT (0x101)

### ISSUE THREAD

**Issue by kennethdz** [Atmosphere-NX/Atmosphere#1539]
### What's the issue you encountered?

I cannot play Burnout: Paradise Remastered or Need for Speed Hot Pursuit, error occurs before main menu. </br>
"Panic occured while running Atmosphere."
"Title ID: 010041544D530000" </br>
"Error: DABRT (0x101)" </br>
Recently updated to 0.19.3 to update my firmware to 11.0.1 to play these games. </br>
I also recently reformatted my SD card from exFAT to FAT32 and created an android partition using Hekate </br>

### How can the issue be reproduced?

[ * ]</br>
Only happens when I try to play those two games</br>

### Crash Report

https://github.com/kennethdz/Atmosphere-Error-Reporting

### System Firmware Version

11.0.1 AMS 0.19.3</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate 
- Official release or unofficial build: official 5.5.6
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: sigpatches are on the SD card as well.
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: SysNAND
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

- All other games I own work perfectly. It's just these two I've encountered this problem.

**Comment by SciresM** [comment]
The report you uploaded is not the report relevant to the crash you mentioned.

Please upload the relevant fatal error report binary, the path to the file is mentioned when the error occurs.

**Comment by kennethdz** [comment]
https://github.com/kennethdz/Fatal-Error-Binary

**Comment by kennethdz** [comment]
https://github.com/kennethdz/Atmosphere-Error-Reporting

**Comment by SciresM** [comment]
This is an error in atmosphere 0.19.3 regarding nullptr hostnames in dns.mitm that was resolved for 0.19.4.

**Comment by kennethdz** [comment]
Just updated to 0.19.4, but I am still unable to play the game. Here is the most recent error binary. 

https://github.com/kennethdz/Atmosphere-Error-Reporting/blob/main/report_2ba141a0.bin

**Comment by SciresM** [comment]
Looks like an error in the wildcardcmp function when processing empty string.

Pushed a fix for it to master.
