### ISSUE TITLE
Panic occurred while running Atmosphere Error: std::abort (0xFFE)

### ISSUE THREAD

**Issue by JulyIghor** [Atmosphere-NX/Atmosphere#2263]
### What's the issue you encountered?

Atmosphere crashed only if specific empty folder created in contents folder

### How can the issue be reproduced?

1) Create an empty folder SD/atmosphere/contents/0100000000001008/romfs/message  
2) Open All-in-One Switch Updater  
3) Select tab "Custom downloads"  
4) Press "Add a custom link"  
5) Enter random text, like "abcd" and press Submit+  
6) Atmosphere crashes with the message:  

```
A fatal error occurred when running Atmosphere.
Program ID: 010041544d530000
Error Desc: std: abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000002cb2b08f.bin
Press POWER to reboot.
```

### Crash Report

[report_000000002cb2b08f.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/13827716/report_000000002cb2b08f.bin.zip)

### System Firmware Version

17.0.0 atmosphere-1.6.2-master-f7bf379cf+hbl-2.4.4+hbmenu-3.6.0

### Environment?

EmuMMC, Hekate, All-in-One Switch Updater

### Additional context?

Possibly this issue related to https://github.com/Atmosphere-NX/Atmosphere/issues/2164 and https://github.com/NX-Family/NX-Translation/issues/3

**Comment by borntohonk** [comment]
> ## Bug Report
> ### What's the issue you encountered?
> 
> Atmosphere crashed only if specific empty folder created in contents folder
> ### How can the issue be reproduced?
> 
>     1. Create an empty folder SD/atmosphere/contents/0100000000001008/romfs/message
> 
>     2. Open All-in-One Switch Updater
This is the atmosphere repository, it has nothing to do with 'All-in-One Switch updater'.
Why are you creating an empty folder in [swkbd](https://switchbrew.org/wiki/Software_Keyboard) in the first place?

**Comment by SciresM** [comment]
@borntohonk as much as what you commented would be correct in 99% of cases, this guy talked to me on discord, and the report he provided actually *is* somehow triggering an svc::ResultInvalidHandle() in ams.mitm, so I think there might be a real atmosphere bug at play.

**Comment by sneakysnakek** [comment]
I am also having this exact issue, anyway to fix it?

**Comment by huypham1411** [comment]
I also got this issue, I tried some method from other related post such as 

- Get your switch in RCM mode. Inject Hekate payload Tap on "Tools" on top of the hekate screen. Tap on "Archive Bit - AutoRCM" on the right bottom. Tap on "Unset archive bit" button. 
- Format sd card to FAT32 (I don't have the FAT32 option)
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/54835897/914b239a-c386-40d4-9ebf-ef31277f2828)

here is the log file
[report_000000000658c023.zip](https://github.com/Atmosphere-NX/Atmosphere/files/14622832/report_000000000658c023.zip)

Hope someone can help. Thanks!

**Comment by Masamune3210** [comment]
On cards bigger that 32GB, you have to use an external tool or application to format to FAT32 since Microsoft in their infinite wisdom decided long ago that they know what the users want better than what the users do. Hekate can do it on the switch itself if you first back up all the contents to your PC so that you don't lose them

**Comment by Masamune3210** [comment]
No, I was saying how to format a sd card that is larger than 32GB as FAT32 since Windows refuses to do so with any of the in-build methods of formatting a media

**Comment by SciresM** [comment]
Huh. I forgot this issue was a thing. I should probably investigate this.

**Comment by TriXGT347** [comment]
hey im getting this issue when booting up undertale or deltarune, literally only those 2 games, im getting the exact same error code too, fr 19.0.1, ams 1.8.0, hekete 6.2.2. did you find a fix? another thing to add is that i get the user selection screen when i only have one user on my  switch and i have it disaballed in system settings.

**Comment by masagrator** [comment]
Not showing user selection works only BEFORE booting the game. It doesn't work when game was not coded to retrieve it automatically from inside.

**Comment by TriXGT347** [comment]
Okay, but have u found a solution?

**Comment by impeeza** [comment]
> Okay, but have u found a solution?

No because is not a Atmosphère issue. We do not support piracy, and this is not a support forum. For support please go to Discord or GBATemp

**Comment by SciresM** [comment]
I'm closing all the atmosphere issues, and while 99% of them are garbage, this one wasn't. Keeping it open because it was a bona-fide atmosphere issue, and I apologize that I've never resolved it.

**Comment by JulyIghor** [comment]
@SciresM thanks for your work! I still hope we get it fixed someday and that way we get fully translated firmware.

**Comment by rashevskyv** [comment]
Cool! Waiting for results. Thank yiu fir your work

**Comment by apischan** [comment]
Please 🙏🏽

**Comment by JulyIghor** [comment]
> I've solved it, I commented ->  _; enable_dns_mitm = u8!0x1_ in the system_settings.ini file in atmosphere\config

Tested and no changes, still black screen at boot if those conflicting folders exist

**Comment by SciresM** [comment]
Yeah, ignore that guy, they have an unrelated issue.

**Comment by themantim486** [comment]
I had the same crash when I:
Selected TOTK on the Home Screen
Closed the account select menu
Selected TOTK again
Fatal Error before account select loaded again

HOS 19.0.1
AMS 1.9.1
I OWN TOTK
Sigpatches on 
Using custom home menu theme
TOTK was heavily modded

**Comment by JoshuaSawagi** [comment]
I have this issue as well and it occurs when I boot up cfw or run ultimate. I tried to clean out my switch sd and I get an Fatal Error. I own Smash Ultimate btw

**Comment by DevanWolf** [comment]
This bug can also occur when `dns_mitm_startup.log` is set to read-only.

**Comment by sskyNS** [comment]
Try using the latest AMS 1.9.4 and all the problems are gone
[https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.9.4](url)

Just a reminder to those who have the same problem as me！

**Comment by JulyIghor** [comment]
Great news - the issue is finally fixed in v1.9.4!

Thanks to this, I can now move forward with releasing an update of [NX-Translation](https://github.com/NX-Family/NX-Translation) that includes a complete translation of all UI elements.

Huge thanks to @SciresM for all the hard work and effort put into tracking down and fixing this. Your dedication makes projects like this possible!

**Comment by Ereza** [comment]
I am still getting this issue with Atmosphère 1.10.1 (with firmware 21.0.1 and now also 21.1.0). It appears to be some kind of concurrency issue, because it is sensitive to timing.

If I use fs.mitm for title `0100000000001008 (swkbd)`, when I go to my user page, then edit my username, the keyboard opens normally. If I close the keyboard (X button), wait one second, and then open it again, everything works as expected. But closing and opening it continuously in shorter amounts of time triggers the fatal error.

This also appears to happen with other titles, like `0100000000001001 (auth)`, which is triggered when parental controls are enabled and you click on the center top icon to disable them: opening the auth screen, then closing it and reopening it again in a fast manner also triggers the same fatal error.

If not using fs.mitm, everything works as expected, of course.

Since comments indicate that it was fixed in 1.9.4, could this still be some concurrency issue that was made more unlikely due to changes for #1972?

My (blind) guess is that something asynchronous is done when using fs.mitm, and if you trigger a relaunch of that title in a shorter amount of time than what it takes that async work to finish, something goes terribly wrong.

I can provide reports if needed, but you should be able to reproduce it (the `swkbd` issue appears to be easier to trigger than the `auth` one).

Maybe this issue should get reopened, @SciresM? Thanks again for all your work!
